/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlcanceRouteImport } from './routes/alcance'
import { Route as WallpapersRouteImport } from './routes/wallpapers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlcanceRoute = AlcanceRouteImport.update({
  id: '/alcance',
  path: '/alcance',
  getParentRoute: () => rootRouteImport,
} as any)
const WallpapersRoute = WallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alcance': typeof AlcanceRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alcance': typeof AlcanceRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alcance': typeof AlcanceRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alcance' | '/wallpapers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alcance' | '/wallpapers'
  id: '__root__' | '/' | '/alcance' | '/wallpapers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlcanceRoute: typeof AlcanceRoute
  WallpapersRoute: typeof WallpapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alcance': {
      id: '/alcance'
      path: '/alcance'
      fullPath: '/alcance'
      preLoaderRoute: typeof AlcanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallpapers': {
      id: '/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof WallpapersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlcanceRoute: AlcanceRoute,
  WallpapersRoute: WallpapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
